Definition release_lock_AT_spec adt := ...
  let l' := TEVENT cpu (TTICKET REL_LOCK)::TEVENT cpu (TSHARED(OATE(AT adt)))::l
  in match H_CalLock l' with Some _ => Some (adt { ... l' ...}) | None => None ... 